name       : xmlrpc-c
version    : 1.39
release    : 3
source     :
    - https://netcologne.dl.sourceforge.net/project/xmlrpc-c/Xmlrpc-c%20Super%20Stable/1.39.12/xmlrpc-c-1.39.12.tgz : d830f3264a832dfe09f629cc64036acfd08121692526d0fabe090f7ff881ce08
license    : BSD-3-Clause
component  : programming.library
summary    : A lightweigt RPC library based on XML and HTTP
description: |
    XML-RPC is a quick-and-easy way to make procedure calls\nover the Internet. It converts the procedure call into XML \ndocument, sends it to a remote server using HTTP, and gets\nback the response as XML. This library provides a modular implementation of XML-RPC for C and C++.
builddeps  :
    - pkgconfig(libcurl)
setup      : |
    %configure --enable-libxml2-backend
build      : |
    %make -j1  # Parallel builds are fixed in v1.43+
install    : |
    %make_install

    # there is no --disable-static option in configure
    rm -fv $installdir%libdir%/lib*.a
